### PR TITLE
Adding support for rows defined on several lines - solves #2

### PR DESCRIPTION
**Pull request by Lucas-C**
This feature can be enabled like this:
```
var md = require('markdown-it')()
              .use(require('markdown-it-multimd-table'), {enableMultilineRows: true});
```

If it is approved, I guess some doc should also be added to the `README`

### CODE REVIEW

**Comment by redbug312** [comment]
Thanks for the nice and clean codes!
I will publish them as version 3.1.0 in a few days! 😃

**Comment by Lucas-C** [comment]
Thanks !
I added another commit to support nested lists in tables.

**Comment by redbug312** [comment]
I've made some tests and found some corner cases:

The first is related to spaces padding in front of `\`:
```markdown
A         | B
----------|-------
text:     | 1     \
- over    | 2     \
- several |       \
- lines   |
```
would generate an additional `<br>` tag between 1 and 2:
```diff
 <td>
-<p>1<br>
+<p>1
 2</p>
 </td>
```
<br>

The second is that it conflicts to the colspan feature:
```markdown
A         | B
----------|-------
text:     ||\
- over    ||\
- several ||\
- lines   |
```
failed to parse the rows:
```diff
-<tbody></tbody>
-</table>
-<p>text:     ||\</p>
+<tbody>
+<tr>
+<td colspan="2">
+<p>text:</p>
 <ul>
-<li>over    ||\</li>
-<li>several ||\</li>
-<li>lines   |</li>
+<li>over</li>
+<li>several</li>
+<li>lines</li>
 </ul>
+</td>
+<td>
+<p>1
+2</p>
+</td>
+</tr>
+</tbody>
+</table>
```

The first seemed easy to solve by using `trim()`, but I have no idea for the second for now.
Could you help fixing this?

**Comment by Lucas-C** [comment]
Sure, I'm going to add tests for those cases

**Comment by Lucas-C** [comment]
This should be fixed now

**Comment by redbug312** [comment]
I've figured out that in line 129, `\n` confused the evaluation of `rowInfo.columns` and `rowInfo.colspans`, So I made it into consideration.
```javascript
isValidColumn = RegExp.prototype.test.bind(/[^\n]/); // = (s => /[^\n]/.test(s))
rowInfo.columns = columns.filter(isValidColumn);
rowInfo.colspans = countColspan(columns.map(isValidColumn));
```

Also I try using `columns[i].trim()` rather than `columns[i].replace(/^\s+/, '').replace(/ +(\n*)$/, '$1')`. Because it seemed that browsers parse multiple newlines as one space? 🤔

Inform me if you think the changes are fine!

**Comment by Lucas-C** [comment]
As long as the test case pass, I'm OK :)

I'm surprised you found a solution without the double call to `.replace()` on `columns[i]`, but the code is certainly better without it. I needed this to preserve the newlines appended between each lines, in order to have a newline before the Markdown bullet list.

About "browsers parse multiple newlines as one space":
I'm not sure to understand your comment right, but yes in HTML newlines are meaningless

**Pull request merged**
